name: bmi_app
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12

  # Login
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0

  # AI
  google_generative_ai: ^0.4.7

  # Image
  image_picker: ^1.0.7

  # UI
  flutter_svg: ^2.2.3
  flutter_markdown: ^0.7.7+1
  syncfusion_flutter_gauges: ^31.2.15

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/googlelogo_color_272x92dp.png
