// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgp5G-Vx94sBM5ZwZh4CSFD1EwGy8R_-w',
    appId: '1:1061074111697:web:e6c7d40ea67685e162fd61',
    messagingSenderId: '1061074111697',
    projectId: 'dacnbmiapp',
    authDomain: 'dacnbmiapp.firebaseapp.com',
    storageBucket: 'dacnbmiapp.firebasestorage.app',
    measurementId: 'G-Z4JV3P95EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgp5G-Vx94sBM5ZwZh4CSFD1EwGy8R_-w',
    appId: '1:1061074111697:android:e9290e1f25126c8c2309f0',
    messagingSenderId: '1061074111697',
    projectId: 'dacnbmiapp',
    storageBucket: 'dacnbmiapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgp5G-Vx94sBM5ZwZh4CSFD1EwGy8R_-w',
    appId: '1:1061074111697:ios:a40342a6b7a4ab5c62fd61',
    messagingSenderId: '1061074111697',
    projectId: 'dacnbmiapp',
    storageBucket: 'dacnbmiapp.firebasestorage.app',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgp5G-Vx94sBM5ZwZh4CSFD1EwGy8R_-w',
    appId: '1:1061074111697:ios:a40342a6b7a4ab5c62fd61',
    messagingSenderId: '1061074111697',
    projectId: 'dacnbmiapp',
    storageBucket: 'dacnbmiapp.firebasestorage.app',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgp5G-Vx94sBM5ZwZh4CSFD1EwGy8R_-w',
    appId: '1:1061074111697:web:ccd2bf13cafb8c2462fd61',
    messagingSenderId: '1061074111697',
    projectId: 'dacnbmiapp',
    authDomain: 'dacnbmiapp.firebaseapp.com',
    storageBucket: 'dacnbmiapp.firebasestorage.app',
    measurementId: 'G-066EW6QMZ0',
  );
}
